### PR TITLE
Harshita

### PR DESCRIPTION
**Pull request by hharshita1**
Added the mobile view gallery.css and galley.js

### CODE REVIEW

**Review by NeerajK2001 — APPROVED** [review]
Good Job

**Review by NeerajK2001 — APPROVED** [review]

**Review by NeerajK2001 — APPROVED** [review]

**Comment by NeerajK2001** [comment]
Looks Good

**Comment by NeerajK2001** [comment]
Harshita change the names of images on the img folder

**Comment by hharshita1** [comment]
Added css for desktop version too and image name

**Comment by hharshita1** [comment]
Resolved all the the issues

**Pull request merged**
